import { StyleSheet } from 'react-native';
import Color from '../../common/Colors';
export default styles=StyleSheet.create({
container:{
    flex: 1, 
    backgroundColor: Color.whiteGrey
},
view1:{
    backgroundColor: Color.white,
    padding: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  view2:{
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  arrow:{
    width: 24, 
    height: 15, 
    marginEnd: 10
  },
  design:{
    fontSize: 22,
    textAlign: 'center',
    marginLeft: 10,
  },
  viewWell:{
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  image:{
    width: 22,
    height: 22,
    marginRight: 15,
    justifyContent: 'center',
  },
  view3:{
    backgroundColor: Color.white,
    padding: 12,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  view4:{
    width: '88%',
    borderWidth: 1,
    borderRadius: 10,
    flexDirection: 'row',
    height: 45,
    alignItems: 'center',
    backgroundColor: Color.white,
  },
  searchView:{
    backgroundColor: 'transparent',
    height: 42,
    width: '68%',
    borderLeftWidth: 0.5,
    marginLeft: 5,
  },
  input:{
    backgroundColor: 'transparent',
    height: 42,
    width: '100%',
  },
  iconView:{
    width: '12%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  card:{
    marginTop: 15,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Color.white,
    borderRadius: 10,
    width:'92%',
    padding: 10,
    justifyContent: 'space-between',
    paddingVertical: 20,
    marginHorizontal: 20,
  },
  card2:{
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 5,
  },
  text:{
    fontSize: 14,
    fontFamily: 'Poppins-Bold',
  },
  text2:{
        fontFamily: 'Poppins-Bold',
        fontSize: 14,
        marginLeft: 20,
  },
  down:{
      height: 25, 
      width: 25, 
      marginRight: 10
    },
  full:{
    fontSize: 14,
    color: Color.twxt,
    fontFamily: 'Poppins',
    marginLeft: 10,
    alignItems: 'center',
    justifyContent: 'center',
    width: '55%',
  },
  full2:{
    fontSize: 13,
    color: Color.black,
    fontFamily: 'Poppins-Bold',
    width: '40%',
  },
  fullView:{
    flexDirection: 'row',
    flex: 1,
    justifyContent: 'space-between',
    marginTop: 8,
  },
  app:{
    fontSize: 14,
    color:Color.twxt,
    marginLeft: 10,
    fontFamily: 'Poppins',
    alignItems: 'center',
    justifyContent: 'center',
    width: '55%',
    width: '55%',
  },
  app1:{
    fontSize: 13,
    color: '#000',
    fontFamily: 'Poppins-Bold',
    width: '40%',
  },
  appView:{
    flexDirection: 'row',
    flex: 1,
    justifyContent: 'space-between',
    marginTop: 8,
  },
  trade:{
    fontSize: 14,
    color: Color.twxt,
    fontFamily: 'Poppins',
    marginLeft: 10,
    alignItems: 'center',
    justifyContent: 'center',
    width: '55%',
  },
  trade1:{
    fontSize: 13,
    color: Color.black,
    fontFamily: 'Poppins-Bold',
    width: '40%',
  },
  tradeView:{
    flexDirection: 'row',
    flex: 1,
    justifyContent: 'space-between',
    marginTop: 8,
  },
  short:{
    fontSize: 14,
    color: Color.twxt,
    fontFamily: 'Poppins',
    marginLeft: 10,
    alignItems: 'center',
    justifyContent: 'center',
    width: '55%',
  },
  short1:{
    fontSize: 13,
    color: Color.black,
    fontFamily: 'Poppins-Bold',
    width: '40%',
  },
  shortView:{
    flexDirection: 'row',
    flex: 1,
    justifyContent: 'space-between',
    marginTop: 8,
  },
  cardView:{
    marginTop: -10,
    flex: 1,
    width:'92%',
    flexDirection: 'column',
    marginHorizontal: 20,
    backgroundColor: Color.white,
    borderRadius: 8,
    justifyContent: 'space-between',
    paddingHorizontal: 15,
    paddingVertical: 10,
  }
})